export const IMAGES = {
  background1: require('../assets/images/background1.png'),
  exclametory_icon: require('../assets/images/exclametory_icon.png'),
  clock: require('../assets/images/clock.png'),
  downarrow: require('../assets/images/downArrow.png'),
  uparrow: require('../assets/images/upArrow.png'),
  person: require('../assets/images/person.png'),
  graph: require('../assets/images/graph.png'),
  home: require('../assets/images/home.png'),
  trophies: require('../assets/images/trophy.png'),
  research: require('../assets/images/research.png'),
  graphs: require('../assets/images/graphs.png'),
  user: require('../assets/images/user.png'),
  appIcon: require('../assets/images/appIcon.png'),
  message: require('../assets/images/message.png'),
  profile_pic: require('../assets/images/profile.png'),
  logout: require('../assets/images/logout.png'),
  star: require('../assets/images/star.png'),
  greenUpArrow: require('../assets/images/greenUpArrow.png'),
  redDownArrow: require('../assets/images/redDownArrow.png'),
  randomImage: require('../assets/images/randomImage.png'),
};
